"""empty message

Revision ID: 0239cfc95fc6
Revises: 4fba6971cbcb
Create Date: 2022-05-19 15:52:22.518833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0239cfc95fc6'
down_revision = '4fba6971cbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('title_all_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('activity', sa.Column('description_all_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'description_all_values')
    op.drop_column('activity', 'title_all_values')
    # ### end Alembic commands ###
