"""Add currency_conversion table

Revision ID: 055edad613b7
Revises: 0239cfc95fc6
Create Date: 2022-10-05 11:49:44.744755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055edad613b7'
down_revision = '0239cfc95fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_conversion')
    # ### end Alembic commands ###
