"""Add value_usd field to transactions table

Revision ID: 9c2fe0aa03f6
Revises: 055edad613b7
Create Date: 2022-10-06 12:14:36.019345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2fe0aa03f6'
down_revision = '055edad613b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('value_usd', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'value_usd')
    # ### end Alembic commands ###
