"""Add name_all_values column to Organisation table

Revision ID: c6fe2cf16adb
Revises: fdc7716bb5ea
Create Date: 2022-11-02 10:36:23.526062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6fe2cf16adb'
down_revision = 'fdc7716bb5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('name_all_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'name_all_values')
    # ### end Alembic commands ###
