"""Add value_eur field to transactions table

Revision ID: fdc7716bb5ea
Revises: 9c2fe0aa03f6
Create Date: 2022-10-20 17:33:19.586356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc7716bb5ea'
down_revision = '9c2fe0aa03f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('value_eur', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'value_eur')
    # ### end Alembic commands ###
