name: Update codelists
on:
  repository_dispatch:
    types: [update-codelists]
jobs:
  update-codelists:
    name: Update codelists
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update codelists
      run: |
        iati download-codelists
    - name: Create a pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: Codelist update
        committer: CodeforIATI bot <57559326+codeforIATIbot@users.noreply.github.com>
        author: CodeforIATI bot <57559326+codeforIATIbot@users.noreply.github.com>
        branch: codelist-update
        delete-branch: true
        title: Codelist update
        body: Codelist update, sent from [this GitHub Action build](https://github.com/codeforIATI/iati-datastore/actions/runs/${{ github.run_id }}).
        reviewers: markbrough,andylolz
